var movieTitle = 'Amadeus';
movieTitle = 'Arrival';
// movieTitle = 9;
movieTitle.toUpperCase();
var numCatLives = 9;
numCatLives += 1;
// numCatLives = "zero";
var gameOver = true;
gameOver = true;
// gameOver = 'true';
